# Use Cloth Config mod for the descriptions.
---
contributorCosmetic: ''
globalTooltip: false
noMicrosoftTelemetry: true
debug:
  tagsTooltip: true
  debugTooltipMsg: true
  NBTTooltip: true
suppressExperimentalSettingsWarning: false
